server:
  port: 9097

spring:
  application:
    name: configserver
  profiles:
    active: native
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config